services:
  backend:
    image: ghcr.io/manojbelbase/quickgpt-backend:latest
    container_name: quickgpt-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5005:5005"

  frontend:
    image: ghcr.io/manojbelbase/quickgpt-frontend:latest
    container_name: quickgpt-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "80:80"
